(function(){'use strict';
var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},l="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=l;var m="object"===typeof e.exportsNamespace&&e.exportsNamespace?e.exportsNamespace:l;e.exportsNamespace=m;l.Object.freeze(e);var n={envInfo:e,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.13"};l.Object.freeze(n);l.Object.freeze(n.semantics);
var p=l.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},q=l.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},r=0,u=l.WeakMap?new l.WeakMap:null;function v(a){return function(b,c){return!(!b||!b.a||b.a.m!==c||b.a.k!==a)}}function aa(a){for(var b in a)return b}
function w(a,b,c){var d=new a.E(b[c]);if(c<b.length-1){a=a.n;c+=1;for(var g=d.C,f=0;f<g.length;f++)g[f]=w(a,b,c)}return d}function ba(a){switch(typeof a){case "string":return x(y);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?x(z):b<<16>>16===b&&1/b!==1/-0?x(A):x(B):"number"===typeof a?x(C):x(D);case "boolean":return x(E);case "undefined":return x(F);default:return null===a?a.$():a&&a.a&&a.a.h.B?x(ca):a&&a.a?x(a.a):null}}
function da(a){switch(typeof a){case "string":ea||(ea=(new G).e());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+p(65535&(a.charCodeAt(d)|0),c)|0,c=p(31,c),d=-1+d|0;return b;case "number":H||(H=(new I).e());b=H;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.i)b.G[0]=a,b=J(b.u[b.I]|0,b.u[b.H]|0);else{if(a!==a)b=!1,a=2047,c=+l.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+l.Math.pow(2,-1022)){a=+l.Math.pow(2,52);var c=
+l.Math.log(d)/.6931471805599453,c=+l.Math.floor(c)|0,c=1023>c?c:1023,g=d/+l.Math.pow(2,c)*a,d=+l.Math.floor(g),g=g-d,d=.5>g?d:.5<g?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+l.Math.pow(2,-1074),c=+l.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=J(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.v^b.t}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.A():null===u?42:ga(a)}}
function ha(a,b){var c=l.Object.getPrototypeOf,d=l.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=d(a,b);if(void 0!==g)return g;a=c(a)}}function ia(a,b,c){a=ha(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function ja(a,b,c,d){a=ha(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new l.TypeError("super has no setter '"+c+"'.");}
var ga=null!==u?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return da(a);default:if(null===a)return 0;var b=u.get(a);void 0===b&&(r=b=r+1|0,u.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(l.Object.isSealed(a))return 42;r=b=r+1|0;return a.$idHashCode$0=b}return null===a?0:da(a)};this.__ScalaJSExportsNamespace=m;
function K(){this.w=this.E=void 0;this.k=this.n=this.h=null;this.m=0;this.D=null;this.s="";this.d=this.q=this.r=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function L(a,b,c){var d=new K;d.h={};d.n=null;d.D=a;d.s=b;d.d=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function M(a,b,c,d,g,f,h){var k=new K,t=aa(a);f=f||function(a){return!!(a&&a.a&&a.a.h[t])};h=h||function(a,b){return!!(a&&a.a&&a.a.m===b&&a.a.k.h[t])};k.w=g;k.h=c;k.s="L"+b+";";k.d=h;k.name=b;k.isInterface=!1;k.isRawJSType=!!d;k.isInstance=f;return k}
function ka(a){function b(a){if("number"===typeof a){this.C=Array(a);for(var b=0;b<a;b++)this.C[b]=g}else this.C=a}var c=new K,d=a.D,g="longZero"==d?N().y:d;b.prototype=new O;b.prototype.constructor=b;b.prototype.a=c;var d="["+a.s,f=a.k||a,h=a.m+1;c.E=b;c.w=la;c.h={b:1,ba:1,c:1};c.n=a;c.k=f;c.m=h;c.D=null;c.s=d;c.r=void 0;c.q=void 0;c.d=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return f.d(a,h)};return c}
function x(a){if(!a.r){var b=new P;b.o=a;a.r=b}return a.r}K.prototype.getFakeInstance=function(){return this===y?"some string":this===E?!1:this===z||this===A||this===B||this===C||this===D?0:this===ca?N().y:this===F?void 0:{a:this}};K.prototype.getSuperclass=function(){return this.w?x(this.w):null};K.prototype.getComponentType=function(){return this.n?x(this.n):null};K.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.q||(b.q=ka(b)),b=b.q;return w(b,a,0)};
var ma=L(!1,"Z","boolean"),na=L(0,"C","char"),oa=L(0,"B","byte"),pa=L(0,"S","short"),qa=L(0,"I","int"),ra=L("longZero","J","long"),sa=L(0,"F","float"),ua=L(0,"D","double");ma.d=v(ma);na.d=v(na);oa.d=v(oa);pa.d=v(pa);qa.d=v(qa);ra.d=v(ra);sa.d=v(sa);ua.d=v(ua);function Q(){}function O(){}O.prototype=Q.prototype;Q.prototype.e=function(){return this};Q.prototype.x=function(){var a=ba(this).o.name,b=(+(this.A()>>>0)).toString(16);return a+"@"+b};Q.prototype.A=function(){return ga(this)};Q.prototype.toString=function(){return this.x()};var la=M({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.a){var c=a.m||0;return!(c<b)&&(c>b||!a.k.isPrimitive)}return!1});Q.prototype.a=la;function R(){}R.prototype=new O;
R.prototype.constructor=R;R.prototype.e=function(){return this};
function va(a){var b=a.getContext("2d");a.width=a.parentElement.clientWidth|0;a.height=wa().documentElement.clientHeight|0;b.fillStyle="#f8f8f8";b.fillRect(0,0,a.width|0,a.height|0);b.lineWidth=5;b.lineJoin="round";b.beginPath();b.fillStyle="black";var c=xa();a.onmousedown=function(a){return function(){a.p=!0}}(c);a.onmouseup=function(a){return function(){a.p=!1}}(c);a.onmousemove=function(a,b,c){return function(h){var k=a.getBoundingClientRect();c.p&&b.lineTo(+h.clientX-+k.left,+h.clientY-+k.top);
b.stroke()}}(a,b,c)}R.prototype.main=function(a){va(a)};R.prototype.a=M({K:0},"example.ScalaJSExample$",{K:1,b:1});var S=void 0;m.example=m.example||{};m.example.ScalaJSExample=function(){S||(S=(new R).e());return S};function T(){this.F=this.J=null;this.f=0}T.prototype=new O;T.prototype.constructor=T;T.prototype.e=function(){return this};
function wa(){var a;U||(U=(new T).e());a=U;0===(268435456&a.f)&&0===(268435456&a.f)&&(0===(134217728&a.f)&&0===(134217728&a.f)&&(a.J=l,a.f|=134217728),a.F=a.J.document,a.f|=268435456);return a.F}T.prototype.a=M({L:0},"org.scalajs.dom.package$",{L:1,b:1});var U=void 0;function P(){this.o=null}P.prototype=new O;P.prototype.constructor=P;P.prototype.x=function(){return(this.o.isInterface?"interface ":this.o.isPrimitive?"":"class ")+this.o.name};P.prototype.a=M({P:0},"java.lang.Class",{P:1,b:1});
function I(){this.i=!1;this.G=this.u=this.l=null;this.z=!1;this.I=this.H=0}I.prototype=new O;I.prototype.constructor=I;
I.prototype.e=function(){H=this;this.l=(this.i=!!(l.ArrayBuffer&&l.Int32Array&&l.Float32Array&&l.Float64Array))?new l.ArrayBuffer(8):null;this.u=this.i?new l.Int32Array(this.l,0,2):null;this.i&&new l.Float32Array(this.l,0,2);this.G=this.i?new l.Float64Array(this.l,0,1):null;if(this.i)this.u[0]=16909060,a=1===((new l.Int8Array(this.l,0,8))[0]|0);else var a=!0;this.H=(this.z=a)?0:1;this.I=this.z?1:0;return this};I.prototype.a=M({V:0},"scala.scalajs.runtime.Bits$",{V:1,b:1});var H=void 0;
function G(){this.f=!1}G.prototype=new O;G.prototype.constructor=G;G.prototype.e=function(){return this};G.prototype.a=M({X:0},"scala.scalajs.runtime.RuntimeString$",{X:1,b:1});var ea=void 0;function V(){}V.prototype=new O;V.prototype.constructor=V;function ya(){}ya.prototype=V.prototype;function W(){this.p=!1}W.prototype=new O;W.prototype.constructor=W;W.prototype.x=function(){return""+this.p};function xa(){var a=new W;a.p=!1;return a}W.prototype.a=M({Y:0},"scala.runtime.BooleanRef",{Y:1,b:1,c:1});
var F=M({Z:0},"scala.runtime.BoxedUnit",{Z:1,b:1,c:1},void 0,void 0,function(a){return void 0===a}),E=M({N:0},"java.lang.Boolean",{N:1,b:1,c:1,g:1},void 0,void 0,function(a){return"boolean"===typeof a});function X(){this.y=null}X.prototype=new O;X.prototype.constructor=X;X.prototype.e=function(){Y=this;this.y=J(0,0);return this};
function za(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c=(32+q(1E9)|0)-(0!==b?q(b):32+q(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,f=a,h=b;for(a=b=0;0<=c&&0!==(-2097152&h);){var k=f,t=h,ta=g,fa=d;if(t===fa?(-2147483648^k)>=(-2147483648^ta):(-2147483648^t)>=(-2147483648^fa))k=h,t=d,h=f-g|0,k=(-2147483648^h)>(-2147483648^f)?-1+(k-t|0)|0:k-t|0,f=h,h=k,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;k=d>>>1|0;g=g>>>1|0|d<<31;d=k}c=h;if(0===c?-1147483648<=(-2147483648^
f):-2147483648<=(-2147483648^c))c=4294967296*h+ +(f>>>0),f=c/1E9,g=f/4294967296|0,d=b,b=f=d+(f|0)|0,a=(-2147483648^f)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,c%=1E9,f=c|0,h=c/4294967296|0;b=[b,a,f,h];a=""+(b["2"]|0);return""+(4294967296*(b["1"]|0)+ +((b["0"]|0)>>>0))+"000000000".substring(a.length|0)+a}X.prototype.a=M({W:0},"scala.scalajs.runtime.RuntimeLong$",{W:1,b:1,ca:1,c:1});var Y=void 0;function N(){Y||(Y=(new X).e());return Y}
var y=M({M:0},"java.lang.String",{M:1,b:1,c:1,aa:1,g:1},void 0,void 0,function(a){return"string"===typeof a}),z=M({O:0},"java.lang.Byte",{O:1,j:1,b:1,c:1,g:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),D=M({Q:0},"java.lang.Double",{Q:1,j:1,b:1,c:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),C=M({R:0},"java.lang.Float",{R:1,j:1,b:1,c:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),B=M({S:0},"java.lang.Integer",{S:1,j:1,b:1,c:1,g:1},void 0,void 0,function(a){return(a|
0)===a&&1/a!==1/-0}),ca=M({T:0},"java.lang.Long",{T:1,j:1,b:1,c:1,g:1},void 0,void 0,function(a){return!!(a&&a.a&&a.a.h.B)}),A=M({U:0},"java.lang.Short",{U:1,j:1,b:1,c:1,g:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function Z(){this.t=this.v=0}Z.prototype=new ya;Z.prototype.constructor=Z;Z.prototype.x=function(){N();var a=this.v,b=this.t;return b===a>>31?""+a:0>b?"-"+za(-a|0,0!==a?~b:-b|0):za(a,b)};function J(a,b){var c=new Z;c.v=a;c.t=b;return c}
Z.prototype.A=function(){return this.v^this.t};Z.prototype.a=M({B:0},"scala.scalajs.runtime.RuntimeLong",{B:1,j:1,b:1,c:1,g:1});
}).call(this);
//# sourceMappingURL=example-opt.js.map


